### PR TITLE
Attempt to fix music queue x2

### PR DESCRIPTION
**Pull request by IceeMC**
🍌🍌🍌

### CODE REVIEW

**Comment by batshalregmi** [comment]
lol watch this break even more

**Comment by IceeMC** [comment]
this gives me a sadder life.

**Comment by batshalregmi** [comment]
yeah
you should close and delete this

**Comment by batshalregmi** [comment]
and never fix it again

**Comment by IceeMC** [comment]
no u

**Comment by IceeMC** [comment]
rood af

**Comment by batshalregmi** [comment]
no u

**Comment by IceeMC** [comment]
fock off m8

**Comment by erickang21** [comment]
nah im gud

**Comment by batshalregmi** [comment]
no you

**Comment by batshalregmi** [comment]
ice is bullying me

**Comment by IceeMC** [comment]
lmfao i ment ur mums a trap xd

**Comment by IceeMC** [comment]
no u

**Comment by batshalregmi** [comment]
im gonna tell my dad
he works for disc0rd
and ur gonna get banned

**Comment by IceeMC** [comment]
im gunna stop commenting

**Pull request merged**
