### PR TITLE
Add dbl stats

### PR DESCRIPTION
**Pull request by batshalregmi**
idk what you use with aws like env. vars

### CODE REVIEW

**Comment by batshalregmi** [comment]
just get a api key

**Comment by ravener** [comment]
Aws don't use env vars

**Comment by ravener** [comment]
Aws don't use env vars

**Comment by batshalregmi** [comment]
what do they use then lol

**Comment by ravener** [comment]
There's a json we keep keys i think

**Comment by batshalregmi** [comment]
k

**Comment by erickang21** [comment]
why would i want this?

**Comment by ravener** [comment]
Lol

**Comment by batshalregmi** [comment]
cause you can have your stats on the website like https://ekene.is-my-waifu.com/uJAJIoaZx.png

**Comment by fourjr** [comment]
Nope.. You should do this every 30mins instead of on join/leave.

**Comment by batshalregmi** [comment]
its not like hes gonna merge it /shrug im gonna close it

**Pull request merged**
