### PR TITLE
Bot will no longer respond to other bots

### PR DESCRIPTION
**Pull request by batshalregmi**
lol

### CODE REVIEW

**Comment by ravener** [comment]
Interesting way

**Comment by ravener** [comment]
Does it work for u or its just an untested pr lol?

**Comment by batshalregmi** [comment]
it works for me

**Comment by ravener** [comment]
Kk

**Review by erickang21 — COMMENTED** [review]
not sure if I want my bot to ignore other bots :(, but appreciate the effort. enjoy your contributor role

**Pull request merged**
