### PR TITLE
wouldn't this make more sense?

### PR DESCRIPTION
**Pull request by avik-s**

### CODE REVIEW

**Comment by StellaraUmbrix** [comment]
That makes 0 sense.

**Comment by avik-s** [comment]
i thot that cuz it's saying 1 to 1000 instead of 1-100
everywhere else it says 1 to 100

**Comment by StellaraUmbrix** [comment]
Its probably meant to be 1-1000, I will try forking to fix and hope Banana notices it

**Comment by avik-s** [comment]
i thot u were banana the whole time
🤦

**Comment by StellaraUmbrix** [comment]
I'm Inkdd#1000
The guy that got his account terminated by a dick that false reported

**Comment by avik-s** [comment]
I realized

**Comment by StellaraUmbrix** [comment]
mk then

**Comment by ravener** [comment]
Closing due to no activity

**Pull request closed without merging**
