### PR TITLE
Notey for admoonsy

### PR DESCRIPTION
**Pull request by StellaraUmbrix**
:)

### CODE REVIEW

**Comment by ravener** [comment]
do u really have to send a PR for such things, could just open an issue.

**Comment by StellaraUmbrix** [comment]
> do u really have to send a PR for such things, could just open an issue.

yes because this is literally the only way for Banana to have noticed this existing :/

**Comment by ravener** [comment]
I said "open an issue" its also part of github and gets logged in discord just doesn't include changing the code

**Comment by StellaraUmbrix** [comment]
> I said "open an issue" its also part of github and gets logged in discord just doesn't include changing the code

and text files are fun to write :P

**Comment by ghost** [comment]
You seem to be very obsessed with someone you're mad at... ;3

**Comment by vilgot** [comment]
What is going on, tbh, this feels like a fucking joke. You gotta say everyones real name, its so pathetic. And why do it like a month after you left or whatever, and the fact that you got extremly pissed when stonic used alts, you gonna do it? This is hopefully a joke

**Comment by IceeMC** [comment]
He actually did this like thursday, wasn’t a joke lmao. Then he proceeded to ping me and rant about me, does he still have some affection towards me? lmao that’d be so fucking funny if he did.

**Comment by erickang21** [comment]
no more of this BS

**Comment by ravener** [comment]
@bananaboy21 lmao why did u merge it, u could just close PRs without merge

**Pull request merged**
