### PR TITLE
nsfw commands if you want

### PR DESCRIPTION
**Pull request by L3NNY0969**
be lucky i added it i almost died again.

### CODE REVIEW

**Comment by erickang21** [comment]
Keep this open, but I won't accept it now because of these reasons:

1) I haven't decided whether NSFW is a good choice for my bot or not. Most likely, yes.
2) Real (human) NSFW is way too much of an ache on my eyes. I'd rather do simpler stuff like hentai instead. 

Reply with your say, plox. :D

**Comment by batshalregmi** [comment]
give me real women porn or i will kill ur bananas

**Comment by erickang21** [comment]
couldn't imagine our biggest weeb saying that... (jk no hard feelings xd)

**Comment by batshalregmi** [comment]
im not a fucking weeb you head ass and yes hard feelings

**Comment by erickang21** [comment]
[insert thonk emoji here]

**Comment by batshalregmi** [comment]
jk

**Comment by batshalregmi** [comment]
and jk about that

**Comment by erickang21** [comment]
undefined word = "that"

**Comment by batshalregmi** [comment]
ur aunts undefined im gonna email ur dad now

**Comment by erickang21** [comment]
plus that code is for async bitch

**Pull request closed without merging**
